version: 2

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - xvfb
    # https://github.com/tlambert03/setup-qt-libs
    - libegl1
    - libdbus-1-3
    - libxkbcommon-x11-0
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-randr0
    - libxcb-render-util0
    - libxcb-xinerama0
    - libxcb-xinput0
    - libxcb-xfixes0
    - x11-utils
    - libxcb-cursor0
